version: '24.0.7'

services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  # Node api service
  api:
    build: .
    ports:
      # local->container
      - 7000:7000
    environment:
      PORT: 7000
      MONGODB_URI: mongodb+srv://admin:admin@blogdatabase.q9v3zhe.mongodb.net/?retryWrites=true&w=majority
      DB_NAME: blogdatabase
    depends_on: 
      - mongo_db

volumes:
  mongo_db: {}